; Listing generated by Microsoft (R) Optimizing Compiler Version 19.35.32215.0 

	TTL	D:\data\code\gaming-studio-practices\cherno-practices\NewProject\Logger\ARM\Debug\Log.obj
	THUMB
	.drectve

	EXPORT	|?instanceCount@Log@@0HA| [ DATA ]	; Log::instanceCount
	EXPORT	|?messagesLogged@Log@@0HA| [ DATA ]	; Log::messagesLogged
	.bss
|?instanceCount@Log@@0HA| % 0x4				; Log::instanceCount
|?messagesLogged@Log@@0HA| % 0x4			; Log::messagesLogged
	.rdata
|?_Fake_alloc@std@@3U_Fake_allocator@1@B| % 1		; std::_Fake_alloc
	END
