; Listing generated by Microsoft (R) Optimizing Compiler Version 19.35.32215.0 

	TTL	D:\data\code\gaming-studio-practices\cherno-practices\NewProject\Logger\ARM\Debug\Static.obj
	THUMB
	.drectve

	EXPORT	|?ss_Variable@@3HA| [ DATA ]		; ss_Variable
	.data
|?ss_Variable@@3HA| DCD 0x5				; ss_Variable
	END
